"""models

Revision ID: 13f1c1ca3e85
Revises: 0654898a8108
Create Date: 2022-09-25 11:29:23.364511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13f1c1ca3e85"
down_revision = "0654898a8108"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
