"""test

Revision ID: caff5bdff9a7
Revises: 
Create Date: 2022-08-22 17:58:36.794309

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "caff5bdff9a7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyzes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analyzes_types",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specialists",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("photo", sa.String(length=150), nullable=True),
        sa.Column("start_work_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("on_main", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specializations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analyzes_types_analyzes",
        sa.Column("analysis_type_id", sa.BigInteger(), nullable=False),
        sa.Column("analysis_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyzes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["analysis_type_id"],
            ["analyzes_types.id"],
        ),
        sa.PrimaryKeyConstraint("analysis_type_id", "analysis_id"),
    )
    op.create_table(
        "specializations_specialists",
        sa.Column("specialization_id", sa.BigInteger(), nullable=False),
        sa.Column("specialist_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["specialist_id"],
            ["specialists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
        ),
        sa.PrimaryKeyConstraint("specialization_id", "specialist_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("specializations_specialists")
    op.drop_table("analyzes_types_analyzes")
    op.drop_table("specializations")
    op.drop_table("specialists")
    op.drop_table("analyzes_types")
    op.drop_table("analyzes")
    # ### end Alembic commands ###
